version: '3'
services:
  app:
    build: .
    environment:
      - TARGET_URL=${TARGET_URL}
      - DISCORD_WEBHOOK_URL=${DISCORD_WEBHOOK_URL}
    volumes:
      - /etc/localtime:/etc/localtime:rbo
    env_file:
      - .env